Tracker:AddLocations("locations/Bestiary.json")
Tracker:AddLocations("locations/Eden.json")
Tracker:AddLocations("locations/Hello Continent.json")
Tracker:AddLocations("locations/Hyperdimension.json")
Tracker:AddLocations("locations/Lastation.json")
Tracker:AddLocations("locations/Leanbox.json")
Tracker:AddLocations("locations/Lowee.json")
Tracker:AddLocations("locations/PC Continent.json")
Tracker:AddLocations("locations/Planeptune.json")
Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/Virtua Forest Safe Zone.json")
Tracker:AddLocations("locations/Station Area.json")
Tracker:AddLocations("locations/Virtua Forest.json")
Tracker:AddLocations("locations/City Center.json")
Tracker:AddLocations("locations/Under Inverse.json")
Tracker:AddLocations("locations/Planeptune Alley.json")
Tracker:AddLocations("locations/Jet Set Range.json")
Tracker:AddLocations("locations/Otori Forest.json")
Tracker:AddLocations("locations/Zeca Ruins No 1.json")
Tracker:AddLocations("locations/Zeca Ruins No 2.json")
Tracker:AddLocations("locations/Haneda Mountain Range.json")
Tracker:AddLocations("locations/Otori Cave.json")
Tracker:AddLocations("locations/Powerlevel Island.json")
Tracker:AddLocations("locations/Digital Future Land.json")
Tracker:AddLocations("locations/Jet Set Peak.json")
Tracker:AddLocations("locations/Bandicrash.json")
Tracker:AddLocations("locations/Kuzarat Facility 1.json")
Tracker:AddLocations("locations/Wanderer's Cave.json")
Tracker:AddLocations("locations/Rud Arms Sewer N.json")
Tracker:AddLocations("locations/Soni Wetlands.json")
Tracker:AddLocations("locations/Gigo Main Entrance.json")
Tracker:AddLocations("locations/National Factory.json")
Tracker:AddLocations("locations/PS Dimension.json")
Tracker:AddLocations("locations/Anonydeath's Lab.json")
Tracker:AddLocations("locations/Vida Dimension.json")
Tracker:AddLocations("locations/Castle Chambers.json")
Tracker:AddLocations("locations/Lowee Castle Exterior.json")
Tracker:AddLocations("locations/Reload Grasslands.json")
Tracker:AddLocations("locations/Rud Arms Sewer S.json")
Tracker:AddLocations("locations/Metroid Shelter.json")
Tracker:AddLocations("locations/Mines.json")
Tracker:AddLocations("locations/Ario Plateau.json")
Tracker:AddLocations("locations/Luji Plateau.json")
Tracker:AddLocations("locations/Lowee Castle Northern Space.json")
Tracker:AddLocations("locations/Halo Forest.json")
Tracker:AddLocations("locations/Kobaba Ruins.json")
Tracker:AddLocations("locations/Zega Forest.json")
Tracker:AddLocations("locations/Nekutoki Forest.json")
Tracker:AddLocations("locations/EM ES Magma Cave.json")
Tracker:AddLocations("locations/Adaldik Forest.json")
Tracker:AddLocations("locations/Pii Shii Game Factory.json")
Tracker:AddLocations("locations/Do Temple.json")
Tracker:AddLocations("locations/Magma Cave.json")
Tracker:AddLocations("locations/Graphic Pass.json")
Tracker:AddLocations("locations/Extradimensional Space.json")
Tracker:AddLocations("locations/Duo R Ruins.json")
Tracker:AddLocations("locations/Koagura Plateau.json")
Tracker:AddLocations("locations/Suaho Mountain Range.json")
Tracker:AddLocations("locations/Keraga Dimension.json")
Tracker:AddLocations("locations/So Shal Forest.json")