Tracker:AddLocations("locations/Bestiary.json")
Tracker:AddLocations("locations/Eden.json")
Tracker:AddLocations("locations/Hello Continent.json")
Tracker:AddLocations("locations/Hyperdimension.json")
Tracker:AddLocations("locations/Lastation.json")
Tracker:AddLocations("locations/Leanbox.json")
Tracker:AddLocations("locations/Lowee.json")
Tracker:AddLocations("locations/PC Continent.json")
Tracker:AddLocations("locations/Planeptune.json")
Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/Virtua Forest Safe Zone.json")
Tracker:AddLocations("locations/Jet Set Range.json")
Tracker:AddLocations("locations/Jet Set Peak.json")
Tracker:AddLocations("locations/Wanderer's Cave.json")
Tracker:AddLocations("locations/Adaldik Forest.json")
